### ISSUE TITLE
Particles affected by nearby light / are not emissive

### ISSUE THREAD

**Issue by ManaStar** [Superkat32/Explosive-Enhancement#15]
When testing out the mod I noticed that the particles were quite dark in areas that weren't very well lit. This struck me as odd because typically when you picture an explosion they are usually very bright. It's probably a very quick fix and it feels like a bit of a nitpick but I thought I'd report it anyways.

Tested on a minimal instance using the latest 1.20.1 release.

**Comment by Superkat32** [comment]
Yeah, you're right, they aren't emissive. I don't think it would be hard to make the particles emissive, but you never know with this video game sometimes. I'll try to add this as a config option next update(probably enabled by default). Don't really know when that'll happen though, because I'm really busy with other stuff. 

Thank you for pointing this out!

**Comment by Superkat32** [comment]
It looks a LOT better than I thought it would.

https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/f9e3444b-57b3-421a-a246-33dad40cba74

**Comment by Superkat32** [comment]
Added in version 1.2.2! Thanks for the suggestion!
