### ISSUE TITLE
Explotions not work on server if mod is not installed on FORGE server with CONNECTOR MOD

### ISSUE THREAD

**Issue by Y5R** [Superkat32/Explosive-Enhancement#17]
I play on Forge 1.20.1 using connector mod, and explotions effect not showing if mod is not installed on server too

please update Mod description, what server side needed to)

**Comment by Superkat32** [comment]
Explosive Enhancement shouldn't do anything when installed on the server because of this here.

https://github.com/Superkat32/Explosive-Enhancement/blob/master/src/main/resources/fabric.mod.json#L18C2-L18C27

To my knowledge, Connector shouldn't be affecting this enough to make it not work. Are you sure your settings are correct(e.g. particles set to all)?

**Comment by Y5R** [comment]
Yep, anyfing working in singleplayer mode, but on the same settings explotions is not showing then connected to server without installed mod 

Mod instalation on server side fixes this

**Comment by Superkat32** [comment]
Yeah, that's really weird. Somebody else was able to fix another Connector issue by updating their Forgified Fabric API mod thing and deleting the Explosive Enhancement config file(which gets regenerated upon launch), but that was a different situation. I would say maybe try updating everything that might be related(Forgifed Fabric API, Connector, Explosive Enhancement), and try again. Beyond that, I don't have enough knowledge of Forge and Connector to really know where the issue lies.

I also don't have time to setup a test Forge server(never done it before, so will have to do research about it), but I'll try and figure that out later... eventually. Other than that, if you manage to fix the issue one day(or if it fixes itself), you can come back here and leave another comment saying its been fixed, and how you fixed it(if you did anything on purpose).
