### ISSUE TITLE
1.19 - 1.19.2 compatibility?

### ISSUE THREAD

**Issue by Scarlaid** [Superkat32/Explosive-Enhancement#2]
Yeah I woke up from a cave and still using 1.19.2 🗿

Any chance, like the title stated?

**Comment by Superkat32** [comment]
If it doesn't take me too long to do so, and if I don't go mad doing so, then yes! I will certainly try to backport the mod to at least 1.19.2. I'm not sure about 1.19.1 or 1.19.0 since I've never made any mods for those versions(then again, I've only made one for 1.19.2). In theory, it should just be a `gradle.properties` and a change in `ExplosiveEnhancement.java`, then figuring out branches again since I've only barely touched branches.

**Comment by Superkat32** [comment]
The mod seems to be working for 1.19.2 now(~~famous last words, lol~~). I will test it some more tomorrow before releasing it on Modrinth. I'm unsure if the 1.19.2 version will receive any future updates. It sorta depends on how much time future me has.

**Comment by Superkat32** [comment]
The mod has been ported to Minecraft version 1.19.2! If you find any issues, please let me know, as I didn't spend as much time testing it compared to the 1.19.3 version. I don't plan on backporting it any further, unfortunately. 

https://modrinth.com/mod/explosive-enhancement/version/1.0.1-1.19.2

Thanks for the suggestion!
