### ISSUE TITLE
Error when using this mod on a LAN server

### ISSUE THREAD

**Issue by DarkFireNinja** [Superkat32/Explosive-Enhancement#22]
When i try to use this mod on a LAN server with my brother who doesn't have the mod installed (he is using Vanilla Minecraft), he gets this error when he tries to join my world:

**Connection Lost

Unsupported (vanilla?) client!
This server requires modded client to join!**

I'm using Quilt Loader on version 1.20.1 of Minecraft.

**Comment by Superkat32** [comment]
What other mods were you using?

**Comment by DarkFireNinja** [comment]
@Superkat32 I had many mods installed but i'm pretty sure that this issue still occurs even if I only used this mod by itself.

**Comment by Superkat32** [comment]
That's what I'm beginning to think as well because of this response (on another issue you made)

https://github.com/TheCSMods/mc-better-stats/issues/102#issuecomment-1885957314

Due to my unfamiliarity with Quilt, and not enough time to officially support Quilt, I can't guarantee that I'm able to fix this issue for Quilt. I also don't really know if there is anything I can do to fix this issue in general(for Quilt or Fabric). I'll try asking around in a few places, but it is likely that you will have better luck having your brother use the same mods as you.

**Comment by DarkFireNinja** [comment]
@Superkat32 Thanks a lot for the response! I believe that if you fixed it for Fabric then it should work the same for Quilt as well (but I'm not sure, I'm no expert on modding lol).
Let me know if you ever manage to fix this issue. For now i will probably just give the mod to my brother as well.
Thanks again!

**Comment by Thsgun** [comment]
im having the same issue for fabric loader 1.20.4

**Comment by Superkat32** [comment]
For the LAN issue: I'm not planning on fixing it, because I'm not sure if I can fix it. I'm not sure if it is a problem with the mod or the mod loader. As you mentioned though, you should be able to fix it on your side by having your brother use the same mods as you(or you use the same mods as him). If something pops up that allows me to fix it though, I'll look into it!

**Comment by YoshiRulz** [comment]
This also affects Fabric. If you have the Fabric API installed but not this mod, you can't connect to a LAN server of a client with this mod installed. You get a message "Received 10 registry entries..."
