### ISSUE TITLE
Wind charges trigger the mod to show the custom explosive particles

### ISSUE THREAD

**Issue by Daniel99j2** [Superkat32/Explosive-Enhancement#32]
Yes, I understand that Wind Charges are still in development. However, they *are* currently accessible and when 1.21 releases, this issue will be more applicable.

When a wind charge explodes, they cause the custom particles for an expolsion to show, replacing the wind burst particles.
To reproduce,
1. Create a world with experiments
2. Run /summon minecraft:wind_charge ~ ~ ~ {Motion:[0.0d, -1.0d, 0.0d]}
3. Notice that the particles are for normal explosions

![2024-05-04_13 00 11](https://github.com/Superkat32/Explosive-Enhancement/assets/121533735/821d15e0-229b-4fbd-965e-ccb11415d00d)

**Comment by Superkat32** [comment]
Nice catch! The issue makes sense because I believe the wind charge's explosions are still treated as normal explosions(without block/entity damage) in the code.

I might take advantage of this though and make a special effect for wind charge explosions, along with a config option to disable them. I'll look into it when I have the time 😃

**Comment by Superkat32** [comment]
Fixed in 1.2.3(totally didn't forget to mark this as complete yesterday)!
No special wind effect has been added just yet, as I couldn't get it looking the way I wanted just yet. But, I may still do that in the future.
