### ISSUE TITLE
"Default Particles" Aren't Affected by Active Resource Packs

### ISSUE THREAD

**Issue by gylertaydos** [Superkat32/Explosive-Enhancement#40]
Hi all,

I was really hoping to use this mod in conjunction with the resource pack [Better Explosion Particles](https://www.curseforge.com/minecraft/texture-packs/better-explosion-particles) for a nice firery explosion. Unfortunately, the default particles completely override this resource pack. Is there a way to make it so this mod uses whatever active resource pack I have for the extra explosion particles?

**Comment by Superkat32** [comment]
That's strange, because I don't mess with the normal explosion particle at all - only spawning it the same way vanilla does.
Can you try without Explosive Enhancement installed? I wonder if maybe you messed up without realizing (the pack you linked only goes up to a 1.19 snapshot, but may or may not still work on 1.19+ without being listed as so - I just don't know)

If the resource pack does work without Explosive Enhancement installed, can you tell me the Minecraft version your using, Explosive Enhancement version, and a screenshot of your resource pack screen (or just list the packs you have enabled) please?

**Comment by gylertaydos** [comment]
Hi, yes, I'm sorry for taking so long to get back. I'm not sure what I did, but I disabled and re-enabled my resource pack and its working now.

**Comment by Superkat32** [comment]
There's no telling what was wrong initially, but glad to see you got it working!
