### ISSUE TITLE
1.21.3 compatibility [BUG]

### ISSUE THREAD

**Issue by GoldenWarriorM** [Superkat32/Explosive-Enhancement#41]
**What operating systems are you seeing the problem on?**
Windows

**What the loader are you seeing the problem on?**
Fabric

**Describe the bug**
Instant crash

**Steps to reproduce**
Start Minecraft with Fabric API, Sodium and Explosive enhancement on Fabric.

**Log** 
https://mclo.gs/pbZAK8q

**Comment by Superkat32** [comment]
Hi! This is because 1.21.2/3 is not yet supported. A 1.21.2/3 port is in the works, but I'll need more time because 1.21.2 changed a lot of the code for explosions. Notably, the power of the explosion is no longer sent to the client, meaning I'll need some time to figure out how that should be handled.

**Comment by Superkat32** [comment]
Finished! Please let me know if you have any issues.
