### ISSUE TITLE
Crash in 1.3 version

### ISSUE THREAD

**Issue by LordEnder-Kitty** [Superkat32/Explosive-Enhancement#45]
Version 1.2.3-1.21.0 worked completely fine and I only updated it to 1.3.0-1.21-1.21.1.
I saw a similar bug report here but their logs looked different from mine, so, I thought I'd post mine with some additional info to try and help. 

https://mclo.gs/0z6Uxnj

**Comment by Helpbot3000** [comment]
It is also crashing for me.

**Comment by Superkat32** [comment]
I think it is ultimately the same issue: no refMaps loaded.

I'm still unable to recreate this myself, but having you guys come in and confirm this issue is actually really helpful.

I've uploaded a test version to GitHub (found here: https://github.com/Superkat32/Explosive-Enhancement/releases/tag/1.3.1-1.21.1-refmapfixtest - download only the `explosive-enhancement-1.3.1-1.21-1.21.1.jar` file, the others won't help) if one of you are able to test it. I was able to fix this issue on a different Minecraft version this way, so I'm hoping it'll work here as well.

If it works, I'll work on releasing the fix along with a couple other things. And if it doesn't work.... well let's hope that doesn't happen.

**Comment by dylanparry** [comment]
Same problem here. I tried the file you linked to above, and Minecraft launched without crashing at least. I didn't get a chance to test it in game though.

**Comment by pauliesnug** [comment]
@Superkat32 Try launching with Carpet mod, it's directly incompatible with the new version due to the mixin refmap.

**Comment by pauliesnug** [comment]
@Superkat32 The test version worked for me with Carpet mod, which was throwing the error.

**Comment by Superkat32** [comment]
Should be fixed in 1.3.2. Let me know if you guys have any other issues. Thanks everyone!
