### ISSUE TITLE
Explosion animation size should be dynamic to the explosion's blast strength. 

### ISSUE THREAD

**Issue by FlyGuy240** [Superkat32/Explosive-Enhancement#9]
For example, some mods add little bombs that don't do as much damage as TNT, in the event of items/entities giving off explosions stronger or weaker than TNT the animation should change. 

The wither is a nice vanilla example of this, as it's blue skulls can be blinding during the fight. I think this feature is small enough to not be too crazy to implement and would increase some of the quality of life when using the mod :)

**Comment by Superkat32** [comment]
I was actually thinking about this idea yesterday. I think it would be a good addition. I also don't think it would be too hard to implement, but you never know with Minecraft modding as I've found out. I'll try to add it sometime in the future(no idea when), and give you some updates whenever I get working on it.

Does the Wither's blue skulls cause the mod's explosion effect? If so, then that could be considered a bug as I didn't intend for that to get affected.

**Comment by FlyGuy240** [comment]
Yeah the Wither's skulls do the explosion effect. It's kind of cool honestly, but they are rather large in the moment. In theory the issue would be minimized or resolved if the explosions scaled to the power too.

**Comment by Superkat32** [comment]
I didn't know that activated the effect. I'll leave it in(because I have no idea how I would exclude it), but yeah, the dynamic explosion size should hopefully make it easier to see during the Wither fight.

**Comment by Superkat32** [comment]
I plan on adding this feature soon™ whenever Explosive Enhancement 1.2.0 is started. Unsure of a release date estimate. I want to finish another mod before coming back to this one unless a game breaking bug is discovered. I'll give a couple updates via comments whenever I start working on this feature and make some good progress on it.

**Comment by mateus3c** [comment]
> I didn't know that activated the effect. I'll leave it in(because I have no idea how I would exclude it), but yeah, the dynamic explosion size should hopefully make it easier to see during the Wither fight.



> I plan on adding this feature soon™ whenever Explosive Enhancement 1.2.0 is started. Unsure of a release date estimate. I want to finish another mod before coming back to this one unless a game breaking bug is discovered. I'll give a couple updates via comments whenever I start working on this feature and make some good progress on it.

since modrinth unfortunately doesn't have a 'comments' section I came here just to say thank you for making this mod! it is so pleasant to see explosions in game now, It is indeed very satisfactory xD
Also I am very hyped to see this wonderful mod on 1.20 and with this new 1.2.0 update that adds dynamic size for the explosions. Keep up the wonderful job!

**Comment by Superkat32** [comment]
> since modrinth unfortunately doesn't have a 'comments' section I came here just to say thank you for making this mod! it is so pleasant to see explosions in game now, It is indeed very satisfactory xD Also I am very hyped to see this wonderful mod on 1.20 and with this new 1.2.0 update that adds dynamic size for the explosions. Keep up the wonderful job!

Thank you! I put a lot of effort into my mods trying to make them as fun to use as possible!

**Comment by Superkat32** [comment]
Hello! Progress on this feature has been started. I will continue to keep you updated, and even try to send videos/screenshots soon.

**Comment by Superkat32** [comment]
Progress! Fireballs and wither skulls have the same power, and it is easier to showcase the fireball then the skull. Charged creepers and end crystals alsos have the same power I believe. I also added a config option to lower the y coordinate of smaller explosions(fireballs, wither skulls) to make it look better because it doesn't look great otherwise. 

https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/8f4b7b01-1c98-4b17-84f0-be4de4a71690

Any thoughts?

**Comment by FlyGuy240** [comment]
That's looking awesome! I love how that's looking!

My only general recommendation/idea if it's not too hard to implement could be something where charged creepers/any explosion that is stronger than a charged creeper is shown as a mushroom cloud? (Think Fallout Mini-Nuke) 

I love how it is currently and think it's coming along very nicely! I only recommend the above feature since it could add even more character to the mod so there's no pressure with that one if it's too demanding to implement.

**Comment by mateus3c** [comment]
> Progress! Fireballs and wither skulls have the same power, and it is easier to showcase the fireball then the skull. Charged creepers and end crystals alsos have the same power I believe. I also added a config option to lower the y coordinate of smaller explosions(fireballs, wither skulls) to make it look better because it doesn't look great otherwise.
> 
>  hooray.mp4 
> Any thoughts?

This looks amazing! they make the game so much cooler and feel way more dynamic! I love jt, thats such an amazing job, keep up man! you got a real talent for Visual effects!

**Comment by Superkat32** [comment]
> My only general recommendation/idea if it's not too hard to implement could be something where charged creepers/any explosion that is stronger than a charged creeper is shown as a mushroom cloud? (Think Fallout Mini-Nuke)

I think this would actually be really cool. It would be insanely easy to implement code-wise, but art-wise? That... that would take some time. This idea would probably be something I add not this coming update(v1.2), but the next update(v1.3), assuming I'm able to get the animation looking good enough. I also know that the floating jellyfish... things from the Better Nether mod activates an explosion more powerful than the charged creeper(based on my code reading), so that would be really cool to see the animation there!

Other than that, thanks to both of you for your feedback!

**Comment by Superkat32** [comment]
Added in 1.2.0! Thanks for the suggestion!

https://modrinth.com/mod/explosive-enhancement/versions

**Comment by mateus3c** [comment]
just had the time to test it and it looks awesome! thank you so much for the amazing job!
